import { Geist, Geist_Mono ,Fraunces,Indie_Flower} from "next/font/google";
import { Poppins, Patrick_Hand,  } from 'next/font/google';
import "./global.css"



const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Women AI Collection",
  description: "Generated by create next app",
};
const poppins = Poppins({
  subsets: ['latin'],
  weight: ['400', '600', '700'],
  variable: '--font-poppins',
});

const patrick = Patrick_Hand({
  subsets: ['latin'],
  weight: '400',
  variable: '--font-patrick',
});

const fraunces = Fraunces({
  subsets: ["latin"],
  variable: "--font-fraunces",
  display: "swap",
});
const indie = Indie_Flower({
  subsets: ["latin"],
  variable: "--font-indie",
  weight: "400",
  display: "swap",
});

export default function RootLayout({ children }) {
  return (
    <html
      lang="en"
      className={`${geistSans.variable} ${geistMono.variable} ${poppins.variable} ${patrick.variable} ${fraunces.variable} ${indie.variable}`}
    >
      <body className="antialiased bg-[#06061A]">
        {children}
      </body>
    </html>
  );
}
